---
  
- name: Install the latest version of Nginx
  yum:
    name: nginx
    state: latest
    
- name: Set nginx user
  set_fact:
    nginx_user: nginx

# - name: Set httpd_can_network_connect flag on and keep it persistent across reboots
#   ansible.posix.setboolean:
#     name: httpd_can_network_connect
#     state: yes
#     persistent: yes
