---
- name: Install the ELRepo repo gpg key
  rpm_key:
    state: present
    key: https://www.elrepo.org/RPM-GPG-KEY-elrepo.org
- name: Intall elrepo repo
  yum: name=https://www.elrepo.org/elrepo-release-7.el7.elrepo.noarch.rpm
- name: Install kernel
  