---
- name: Install the ELRepo repo gpg key
  rpm_key:
    state: present
    key: https://www.elrepo.org/RPM-GPG-KEY-elrepo.org
- name: Intall elrepo repo
  yum: 
    name: "https://www.elrepo.org/elrepo-release-{{ansible_distribution_major_version}}.el{{ansible_distribution_major_version}}.elrepo.noarch.rpm"
- name: Install kernel
  yum:
    name: kernel-ml
    enablerepo: elrepo-kernel
    state: present
- name: Generate sysctl config
  template:
    src: 99-bbr.conf.j2
    dest: /etc/sysctl.d/99-bbr.conf
    mode: 0644
- name: Make sysctl config take effects
  command: sysctl -p

